### ISSUE TITLE
Problem when running $ yeoman server command

### ISSUE THREAD

**Issue by mariusmateoc** [romainberger/yeoman-wordpress#12]
After I created the project when I run $ yeoman server command it gives me this:

Running "server" task
<FATAL> listen EADDRINUSE </FATAL>
![yeoman server error](https://f.cloud.github.com/assets/2094443/89992/b8f054ac-6561-11e2-85da-d0832722ec0a.png)

And it won't open any page.

**Comment by romainberger** [comment]
Do you have the Live reload software running?

**Comment by mariusmateoc** [comment]
Yes, the LiveReload software was running and that was the problem. Now it's working!

Thanks

**Comment by romainberger** [comment]
Yeah there is a conflict between the ports so the Yeoman server crashes. Kind of annoying to have to stop Live reload every time but sadly there is no solution.

**Comment by mariusmateoc** [comment]
When I start a project with $ yeoman init command then I run $ yeoman server the server starts and open the page even if I have the LiveReload software open. I told you that maybe you can find a solution. 

Yes this is little annoying but I can live with it. :)
