### ISSUE TITLE
Invalid namespace: init (or not yet registered)

### ISSUE THREAD

**Issue by kaidez** [romainberger/yeoman-wordpress#14]
I'm trying to init in my directory but get a 'Invalid namespace: init (or not yet registered)' message when I do.

I'm running 'yo init yeoman-wordpess' as 'yo' is the new trigger for yeoman.

I checked and the files made the generators directory.  Running yeoman v 1.0.0-beta.3.

Any ideas?  Thanks in advance.

**Comment by romainberger** [comment]
Hi, I haven't worked on making the generator work with Yeoman 1.0 for now and some stuff have to be adapted.
I'll try to fix this during the week end.
Sorry for the delay, I'll keep you posted.

**Comment by kaidez** [comment]
No problem...thanks for clarifying!!!
