### ISSUE TITLE
Error trying to compile coffeescript

### ISSUE THREAD

**Issue by bigardone** [romainberger/yeoman-wordpress#18]
Hi!
I'm trying to add a new coffeescript file to my theme but yeoman's server aborts due to the following error:

```
Running "coffee:dist" (coffee) task
<WARN> Unable to write "app/wp-content/themes/enfermeria/js" file (Error code: EISDIR). Use --force to continue. </WARN>

Aborted due to warnings.
```

Everything else works fine.

Any ideas of why is this error happening?
Thanks in advance!

**Comment by romainberger** [comment]
Hi,

You can fix this in the Gruntfile by replacing the line 22 with:

```
    dest: 'app/wp-content/themes/mytheme/js/*.js'
```

Sorry about that, I've never used coffescript so I never had this error.
I fixed the generator so it shouldn't happen. Thanks for reporting this!

**Comment by bigardone** [comment]
Now it works like a charm!
Thanks!
