### ISSUE TITLE
error: ENOENT

### ISSUE THREAD

**Issue by davidwmartin** [romainberger/yeoman-wordpress#19]
Trying to set up a wordpress build, here is the console activity:

new-host-4:dreams bassdrum99$ yo yo-wordpress

```
Trying to get the latest stable version of Wordpress
Latest version: 3.5.1
Name of the theme you want to use: (mytheme) 
Starter theme (please provide a github link): (https://github.com/automattic/_s) https://github.com/fffunction/sassaparilla.git
Which version of Wordpress do you want? (3.5.1) 
Would you like to include RequireJS (for AMD support)? (Y/n) y
Author name: wes
Author URI: 

/usr/local/lib/node_modules/bower/node_modules/tmp/lib/tmp.js:219
    throw err;
          ^
Error: ENOENT, open '/Users/bassdrum99/.yeoman/yeoman-wordpress/config.json'
```

Don't know what to do, and I couldn't find any information on how to resolve this issue. Any help would be much appreciated.

**Comment by romainberger** [comment]
There must be an error in the config file. Weird that it's triggered here, it's supposed to have already read it at this point.
Could you show me the content of the file `/Users/bassdrum99/.yeoman/yeoman-wordpress/config.json` so I can see what is causing the error ?
I'll fix the generator to avoid crashing if this happens.

**Comment by davidwmartin** [comment]
There is no folder ".yeoman" in /users/bassdrum99 (yes, I have enabled viewing of hidden folders). In fact, I can't seem to find that folder anywhere on my computer. I assume this is then a bigger problem with my yeoman install?

**Comment by kymmt** [comment]
i had same issue on my mac.

**Comment by popmatik** [comment]
Hello! I've also had this issue today. Shame as I really want to check out what you have done, it looks amazing! Any ideas on a fix? 

I'm using yeoman 1.0 if that makes any difference. 

Cheers

**Comment by romainberger** [comment]
Sorry I haven't had any time to work on a fix for now. 

> I assume this is then a bigger problem with my yeoman install?

Not necessarily. The `~/.yeoman` was a folder created with the < 1.0 Yeoman version but I never checked if the new version still use it as I never ran into this issue.

I will try to fix it tonight!
