### ISSUE TITLE
Can't find the generator

### ISSUE THREAD

**Issue by jahvi** [romainberger/yeoman-wordpress#2]
I tried to use the this generator but I haven't been able to run it, I installed it with:

`npm install yeoman-wordpress`

But when I try to run `yeoman init yeoman-wordpress` I get "Could not find generator yeoman-wordpress".  It shows a bunch of folders where it tries to look for it but apparently it's unable to find it.

**Comment by romainberger** [comment]
Hi,
You will find the solution here: https://github.com/romainberger/yeoman-wordpress/issues/1

I definitely have to add this to the readme!

**Comment by jahvi** [comment]
Perfect works fine now thanks
