### ISSUE TITLE
grunt says no gruntfile recognized even though it's right there?

### ISSUE THREAD

**Issue by mgenev** [romainberger/yeoman-wordpress#26]
I'm not sure what is happening, but grunt wont't run, it says there is no gruntfile. 

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

**Comment by mgenev** [comment]
it also talks about using require, but I'm not seeing it hooked up anywhere... I really like the direction this is going, but is it unfinished? or is my node/yeoman screwing up...

**Comment by romainberger** [comment]
Wow, tough one. Never came across this problem... What command do you run when you get this error?

And for the require thing, it only adds the library in the theme but doesn't do anything more. 
I am no longer improving this generator as I don't personally use it anymore (I try to stay away as much as possible from wordpress). I still take care of fixing issues and upgrading stuffs when needed,  but I don't plan on adding anything.

**Comment by mgenev** [comment]
just "grunt" with or without any options. Thanks for your help.

Do you know of a better CMS if you're giving up on wordpress?

**Comment by romainberger** [comment]
Okay, I'll try to see what I can do, but it might be hard to find as we might have different configurations and versions of the tools.

About wordpress I tend to prefer frameworks over CMS, plus I am trying to move from php to others languages. But it's still useful to quickly set up a blog for clients.

**Comment by tjtate** [comment]
yea this is an issue for me as well, its not adding any devDependencies to the package.json and its not loading any npm tasks in the gruntfile. ill try to put in a pull request for this.

**Comment by mgenev** [comment]
give this a try https://github.com/mgenev/yoWebAppWP

**Comment by tjtate** [comment]
nice! thanks ill check it out!

**Comment by GabLeRoux** [comment]
Same issue here, no `devDependencies`.

My generated `Package.json` file

```
{
  "author": "",
  "name": "",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {}
}
```

**Comment by crockett95** [comment]
Yeah, I had the same issue, and the `Gruntfile.js` doesn't work quite right. I'm messing with this on my fork under the `grunting` branch to see if I can get it fixed. Seems to be:
- May or may not run `npm install` on creation (I haven't looked yet)
- No `devDependencies` for grunt on creation
- No tasks registered to grunt from `devDependencies` in `Gruntfile.js`
- No default task, only `grunt test`

I don't know if anything else is going on, I just started on it about an hour ago.

**Comment by tjtate** [comment]
I have since switched to using https://github.com/mattbanks/WordPress-Starter-Theme, this has support for grunt tasks, compass, built in bower support (shameless contribution by me) and matt is pretty responsive with updates. This is only a theme, but after thinking about my own process I much prefer to have wordpress under the wordpress svn and have all the goodieness (node_modules, etc) in the theme itself.

**Comment by mgenev** [comment]
tjtate, excellent, thanks!

**Comment by bigardone** [comment]
+1
I have the same problem while executing grunt server:

```
grunt-cli: The grunt command line interface. (v0.1.9)
Fatal error: Unable to find local grunt.
```

**Comment by romainberger** [comment]
All right, found what's going on (I haven't used grunt and yo in a long time so I needed to refresh my skills). Started working on a fix in the [grunt-fix](https://github.com/romainberger/yeoman-wordpress/tree/grunt-fix) branch. Still needs some work to be sure everything's working, I'll try to finish this tonight.

**Comment by bigardone** [comment]
Great! Thanks in advance :)

**Comment by romainberger** [comment]
Rewrote the package.json and Gruntfile, this should work now. 

And sorry I forgot this issue and spent 3 month before fixing it :thumbsdown:

**Comment by bigardone** [comment]
Yes, now it works like a charm. Thanks!
