### ISSUE TITLE
Fatal Error on 'yeoman init yeoman-wordpress'

### ISSUE THREAD

**Issue by reneruiz** [romainberger/yeoman-wordpress#3]
UNKNOWN, unknown error '/Users/rruiz/projects/research-and-development/app'

**Comment by romainberger** [comment]
Never seen this error...
Can you give me some more details on how it happened? Like how did you install the generator, does this happen with other generators?
Also the 'app' directory is the directory where you're trying to create the project or is it the app folder of a yeoman app you created before?

**Comment by reneruiz** [comment]
Turns out I had a much deeper problem with yeoman. All good now.
