### ISSUE TITLE
Getting the latest version of Wordpress...

### ISSUE THREAD

**Issue by karbassi** [romainberger/yeoman-wordpress#4]
As long as WP keeps naming their versions with sequential numbers, you can do the following command.

``` bash
svn ls http://svn.automattic.com/wordpress/tags/ | tail -n 1
```

Not the final answer but it should give you ideas of how to automate the automatic version tracking.

**Comment by romainberger** [comment]
Nice solution, I didn't know this svn command.
I wonder if it's the perfect solution though as it assumes the user has svn installed. I don't know if there are a lot of developers who doesn't but I guess you can't be 100% sure. But with a fallback in case this doesn't work, it could be great.

I was thinking about parsing the rss feed Wordpress provides which is updated with every stable version, but I had some trouble with a node modules.

Anyway, thanks the help, the version tracking is the thing I am currently working on to improve the generator so I will keep that in mind.

**Comment by ErikFontanel** [comment]
Isn't it a better idea to pull wordpress from git, https://github.com/WordPress/WordPress and check out the latest stable tag (3.4.2 for now). The nice thing is about this gitrepo, it also has the unstable alphas and betas so the developer can decide which version to use.

**Comment by romainberger** [comment]
The framework is downloaded from the git repo. 
With `git ls-remote --tags git://github.com/WordPress/WordPress.git | tail -n 1` I can get the last tag, I will try to implement this tonight.

The generator prompts the user which version he wants to use, so you can get any version you want.

**Comment by romainberger** [comment]
Thanks @karbassi I've used your suggestion and it works really well.
