### ISSUE TITLE
Z_DATA_ERROR

### ISSUE THREAD

**Issue by wmena** [romainberger/yeoman-wordpress#40]
unzip error { [Error: incorrect header check] errno: -3, code: 'Z_DATA_ERROR' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)

**Comment by romainberger** [comment]
What command did you run?

**Comment by dovfriedman** [comment]
same error running -

```
yo yo-wordpress
```

**Comment by wmena** [comment]
Sorry for the late replay.

yo yo-wordpress:plugin

**Comment by romainberger** [comment]
Fixed in 5c5e40f2d5a2f698ed022f9281159da2477bb6e6

@dovfriedman I'm not getting any error with the app generator. If you still run into this issue can you please open a issue with the full stack trace? thanks
