### ISSUE TITLE
The new update is broken

### ISSUE THREAD

**Issue by wmena** [romainberger/yeoman-wordpress#42]
is not unzipping the wordpress file and the _s theme

**Comment by dabernathy89** [comment]
same issue with the plugin - this.tarball() doesn't seem to be working. i'm guessing it's an issue with yo, and not the generator.

Mac OS X 10.9 (mavericks), yo 1.0.4, node 0.10.21

```
Daniels-MacBook-Air:test danielabernathy$ yo yo-wordpress:plugin
[?] Name of the plugin: Some Plugin
[?] Author Name: Daniel

 info ... Fetching https://github.com/tommcfarlin/WordPress-Plugin-Boilerplate/tarball/master ...
 info This might take a few moments
..............................✔ Done in app/wp-content/plugins


/usr/local/lib/node_modules/generator-yo-wordpress/plugin/index.js:69
    if (err) throw err
                   ^
Error: ENOENT, open 'app/wp-content/plugins/SomePlugin/SomePlugin.php'
```

**Comment by romainberger** [comment]
@dabernathy89 I don't think this error is related. Yours is caused by a file that is not found.

**Comment by dabernathy89** [comment]
@romainberger It's not finding the file because the tarball wasn't extracted. right now the only file in the 'plugins' directory is 'master' (no file extension)

**Comment by romainberger** [comment]
Ah yeah ok. Although if the `tarball` method would fail it should throw an error? Anyway I'll take a look asap.

_Edit_: the lack of extension is weird though

**Comment by jaspervalero** [comment]
+1 I'm having the same issue on OS X 10.9 Mavericks, yo 1.0.4, node 0.10.21.

![image](https://f.cloud.github.com/assets/845659/1458647/124f8518-438d-11e3-904f-f8d3f97b0200.png)

**Comment by rezzafr33** [comment]
i think we should change the tarballLink to something like this https://github.com/yeoman/generator/archive/master.tar.gz , instead of https://github.com/yeoman/generator/tarball/master
