### ISSUE TITLE
Use `YeoPress` as the default theme name

### ISSUE THREAD

**Issue by neojp** [romainberger/yeoman-wordpress#45]
`twentytwelve` is included by default with WordPress, I don't think it makes much sense to use it as the default directory name, specially since you include your YeoPress theme as the default theme to be downloaded from GitHub.

![yo-wordpress-theme-directory](https://f.cloud.github.com/assets/127994/1475805/16f3dba8-4641-11e3-91ac-163b24f0587f.png)

**Comment by romainberger** [comment]
I'm afraid you're in the wrong repo... [this must be what you're looking for](https://github.com/wesleytodd/YeoPress)

**Comment by neojp** [comment]
Oh damn, sorry @romainberger. I was looking at your project at the same time and got them confused.

**Comment by romainberger** [comment]
Ahah no problem :smile: I guess that's the same for #44 and #46 ?

**Comment by neojp** [comment]
What?! No way.. I'm so sorry, Romain. Is there a way to delete issues on GitHub?

**Comment by romainberger** [comment]
I don't think there is. Don't worry, that happens
