### ISSUE TITLE
Improvements on generator

### ISSUE THREAD

**Issue by pgom** [romainberger/yeoman-wordpress#5]
I've been using this generator (great stuff, btw) as starter to one of my projects. I'm also using, roots as a wordpress starter theme and they create a grunt file for their build, as seen:

https://github.com/retlehs/roots/tree/grunt 

I'm getting nice results working with it on yeoman, so maybe you would like to take a look. I can work with you on that...if you like.

**Comment by romainberger** [comment]
I just tried it and it's interesting.
So how do you use it with Yeoman? Do you use their build script or a combination of both?
I find it kind of annoying that you have to install two other package to be able to use it, though. It's not really an issue, but it just make it less usable right out of the box.

And to be honest, Wordpress is not the framework I use the most, I am opened to suggestions from people who have more experience. So if you want to contribute, I am definitely ok!

**Comment by pgom** [comment]
Right now, I'm using a combination of both, i.e, I use some tasks from yeoman and other from that gruntfile. I found quite annoying too...but it only took me one 'npm install' ;) 
More annoying, for me, is that I had to change the yeoman.js where the tasks are defined and add one to this specific project. I'ts kind of an issue that yeoman doesn't allow (not that I'm aware of) to register custom tasks. 

But I'm definitely keep trying this out and contribute as much as I can. I'll keep you posted...

**Comment by romainberger** [comment]
I am closing these issues as I haven't made any progress on the build task and don't plan to make any.
I personnaly avoid as much as possible working with Wordpress right now and don't use this generator very often,
so I don't have a need for this.

I still keep the `build` branch if anyone is interested and I will continue to update and fix the issues in the generator if there are some.
